### PR TITLE
Added modulemap

### PR DESCRIPTION
**Pull request by andrewmalek27**
Added module map to allow importing in Swift as framework without bridging header.

screen shot 2017-05-23 at 6 10 41 pm

### CODE REVIEW

**Comment by asmith-prosper** [comment]
@rlagadapati could you take a look at this PR from Andrew at Clarity?

**Comment by rlagadapati** [comment]
@asmith-prosper Changes looks fine.

**Comment by andrewmalek27** [comment]
I reverted back to 1.10 and fixed what was potentially a typo in the pod spec version (1.0.10 -> 1.10)

**Comment by andrewmalek27** [comment]
Can you guys please merge this? Thanks

**Comment by rlagadapati** [comment]
@andrewmalek27 I will update the new pod version when publishing the new framework.

**Pull request closed without merging**
